sudo: required
services:
  - docker

before_install:
  - docker build -t kfclts/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kfclts/react-test npm run test -- --coverage


after_success:
  - docker build -t kfclts/multi-client ./client
  - docker build -t kfclts/multi-nginx ./ngix
  - docker build -t kfclts/multi-server ./server
  - docker build -t kfclts/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kfclts/multi-client
  - docker push kfclts/multi-nginx
  - docker push kfclts/multi-server
  - docker push kfclts/multi-worker